Style/ClassAndModuleChildren:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MultipleComparison:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Layout/EmptyLinesAroundArguments:
  Exclude:
    - 'spec/resource/serializable_spec.rb'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  Enabled: false

Metrics/LineLength:
  Max: 130

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 35

Metrics/PerceivedComplexity:
  Max: 15

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/BlockLength:
  Enabled: false

Lint/UnifiedInteger:
  Enabled: false

Performance/RegexpMatch:
  Enabled: false
