language: ruby
rvm:
  - 2.1.9
  - 2.1.10
  - 2.2.7
  - 2.3.2
  - 2.3.4
  - 2.4.1
before_install: gem install bundler -v 1.10.5

gemfile:
  - gemfiles/3.2.gemfile
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile

matrix:
  exclude:
    - gemfile: gemfiles/5.0.gemfile
      rvm:
        - 2.1.10
        - 2.1.9

