language: ruby
rvm:
  - 2.4.0
before_install: gem install bundler -v 2.2.0

gemfile:
  - gemfiles/3.2.gemfile
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile

matrix:
  exclude:
    - rvm: 2.1.9
      gemfile: gemfiles/5.0.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/5.0.gemfile

